


pool:
  vmImage: ubuntu-latest
  
stages:

#### Build App Stage ###
- stage: build_app
  dependsOn: []
  jobs:
  - job: build_app
    displayName: build_app
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      displayName: mvn package
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package -P$(lib_stage)'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false








  