
trigger: none 

variables:

  azureSubscription: 'b8994bcf-35bc-4859-a121-36288ee1dbf5'

  webAppName: 'controlwebapp'

  environmentName: 'controlwebapp'

pool:
  vmImage: ubuntu-latest
  
stages:

#### Build App Stage ###
- stage: build_app
  displayName: "build-validation"
  jobs:
  - job: build_app
    displayName: build-validation
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      displayName: mvn package
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false


    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop


- stage: Deploy
  displayName: Deploy stage
  dependsOn: build_app
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: controlwebapp'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'







  