
pool:
  vmImage: ubuntu-latest
  
stages:

#### Build App Stage ###
- stage: build_app
  dependsOn: []
  jobs:
  - job: build_app
    displayName: build_app
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      displayName: mvn package
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package -P$(lib_stage)'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: AzureCLI@2
      displayName: docker build && docker push
      inputs:
        azureSubscription: $(lib_service_conn)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(lib_container_registry)
          docker build -t $(var_service_name) -f pipeline/docker/Dockerfile --build-arg stage=$(lib_stage) .
          docker tag $(var_service_name) $(lib_container_registry)/$(var_service_name)
          docker push $(lib_container_registry)/$(var_service_name)






  